/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file rpkiRtrPrefixOriginTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef RPKIRTRPREFIXORIGINTABLE_DATA_GET_H
#define RPKIRTRPREFIXORIGINTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rpkiRtrPrefixOriginTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * RPKI-RTR-MIB::rpkiRtrPrefixOriginTable is subid 4 of rpkiRtrObjects.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.218.1.4, length: 9
     */
    /*
     * indexes
     */



    int            
        rpkiRtrPrefixOriginTable_indexes_set_tbl_idx
        (rpkiRtrPrefixOriginTable_mib_index * tbl_idx,
         u_long rpkiRtrPrefixOriginAddressType_val,
         char *rpkiRtrPrefixOriginAddress_val_ptr,
         size_t rpkiRtrPrefixOriginAddress_val_ptr_len,
         u_long rpkiRtrPrefixOriginMinLength_val,
         u_long rpkiRtrPrefixOriginMaxLength_val,
         u_long rpkiRtrPrefixOriginASN_val,
         u_long rpkiRtrPrefixOriginCacheServerId_val);
    int            
        rpkiRtrPrefixOriginTable_indexes_set
        (rpkiRtrPrefixOriginTable_rowreq_ctx * rowreq_ctx,
         u_long rpkiRtrPrefixOriginAddressType_val,
         char *rpkiRtrPrefixOriginAddress_val_ptr,
         size_t rpkiRtrPrefixOriginAddress_val_ptr_len,
         u_long rpkiRtrPrefixOriginMinLength_val,
         u_long rpkiRtrPrefixOriginMaxLength_val,
         u_long rpkiRtrPrefixOriginASN_val,
         u_long rpkiRtrPrefixOriginCacheServerId_val);




#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRPREFIXORIGINTABLE_DATA_GET_H */
/** @} */
