/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file rpkiRtrCacheServerTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef RPKIRTRCACHESERVERTABLE_DATA_GET_H
#define RPKIRTRCACHESERVERTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rpkiRtrCacheServerTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * RPKI-RTR-MIB::rpkiRtrCacheServerTable is subid 2 of rpkiRtrObjects.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.218.1.2, length: 9
     */
    /*
     * indexes
     */

    int            
        rpkiRtrCacheServerLocalAddressType_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerLocalAddressType_val_ptr);
    int            
        rpkiRtrCacheServerLocalAddress_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         char **rpkiRtrCacheServerLocalAddress_val_ptr_ptr,
         size_t *rpkiRtrCacheServerLocalAddress_val_ptr_len_ptr);
    int            
        rpkiRtrCacheServerLocalPort_get(rpkiRtrCacheServerTable_rowreq_ctx
                                        * rowreq_ctx,
                                        u_long *
                                        rpkiRtrCacheServerLocalPort_val_ptr);
    int            
        rpkiRtrCacheServerPreference_get(rpkiRtrCacheServerTable_rowreq_ctx
                                         * rowreq_ctx,
                                         u_long *
                                         rpkiRtrCacheServerPreference_val_ptr);
    int            
        rpkiRtrCacheServerConnectionType_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerConnectionType_val_ptr);
    int            
        rpkiRtrCacheServerConnectionStatus_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerConnectionStatus_val_ptr);
    int            
        rpkiRtrCacheServerDescription_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         char **rpkiRtrCacheServerDescription_val_ptr_ptr,
         size_t *rpkiRtrCacheServerDescription_val_ptr_len_ptr);
    int            
        rpkiRtrCacheServerMsgsReceived_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerMsgsReceived_val_ptr);
    int            
        rpkiRtrCacheServerMsgsSent_get(rpkiRtrCacheServerTable_rowreq_ctx *
                                       rowreq_ctx,
                                       u_long *
                                       rpkiRtrCacheServerMsgsSent_val_ptr);
    int            
        rpkiRtrCacheServerV4ActiveRecords_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV4ActiveRecords_val_ptr);
    int            
        rpkiRtrCacheServerV4Announcements_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV4Announcements_val_ptr);
    int            
        rpkiRtrCacheServerV4Withdrawals_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV4Withdrawals_val_ptr);
    int            
        rpkiRtrCacheServerV6ActiveRecords_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV6ActiveRecords_val_ptr);
    int            
        rpkiRtrCacheServerV6Announcements_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV6Announcements_val_ptr);
    int            
        rpkiRtrCacheServerV6Withdrawals_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerV6Withdrawals_val_ptr);
    int            
        rpkiRtrCacheServerLatestSerial_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerLatestSerial_val_ptr);
    int            
        rpkiRtrCacheServerSessionID_get(rpkiRtrCacheServerTable_rowreq_ctx
                                        * rowreq_ctx,
                                        u_long *
                                        rpkiRtrCacheServerSessionID_val_ptr);
    int            
        rpkiRtrCacheServerRefreshTimer_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long * rpkiRtrCacheServerRefreshTimer_val_ptr);
    int            
        rpkiRtrCacheServerTimeToRefresh_get
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         long *rpkiRtrCacheServerTimeToRefresh_val_ptr);
    int            
        rpkiRtrCacheServerId_get(rpkiRtrCacheServerTable_rowreq_ctx *
                                 rowreq_ctx,
                                 u_long * rpkiRtrCacheServerId_val_ptr);


    int            
        rpkiRtrCacheServerTable_indexes_set_tbl_idx
        (rpkiRtrCacheServerTable_mib_index * tbl_idx,
         u_long rpkiRtrCacheServerRemoteAddressType_val,
         char *rpkiRtrCacheServerRemoteAddress_val_ptr,
         size_t rpkiRtrCacheServerRemoteAddress_val_ptr_len,
         u_long rpkiRtrCacheServerRemotePort_val);
    int            
        rpkiRtrCacheServerTable_indexes_set
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
         u_long rpkiRtrCacheServerRemoteAddressType_val,
         char *rpkiRtrCacheServerRemoteAddress_val_ptr,
         size_t rpkiRtrCacheServerRemoteAddress_val_ptr_len,
         u_long rpkiRtrCacheServerRemotePort_val);




#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRCACHESERVERTABLE_DATA_GET_H */
/** @} */
