/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef RPKIRTRCACHESERVERTABLE_INTERFACE_H
#define RPKIRTRCACHESERVERTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "rpkiRtrCacheServerTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _rpkiRtrCacheServerTable_initialize_interface
        (rpkiRtrCacheServerTable_registration * user_ctx, u_long flags);
    void           
        _rpkiRtrCacheServerTable_shutdown_interface
        (rpkiRtrCacheServerTable_registration * user_ctx);

    rpkiRtrCacheServerTable_registration
        *rpkiRtrCacheServerTable_registration_get(void);

    rpkiRtrCacheServerTable_registration
        *rpkiRtrCacheServerTable_registration_set
        (rpkiRtrCacheServerTable_registration * newreg);

    netsnmp_container *rpkiRtrCacheServerTable_container_get(void);
    int             rpkiRtrCacheServerTable_container_size(void);
    netsnmp_cache *rpkiRtrCacheServerTable_cache_get(void);

    rpkiRtrCacheServerTable_rowreq_ctx
        *rpkiRtrCacheServerTable_allocate_rowreq_ctx(void);
    void           
        rpkiRtrCacheServerTable_release_rowreq_ctx
        (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx);

    int             rpkiRtrCacheServerTable_index_to_oid(netsnmp_index *
                                                         oid_idx,
                                                         rpkiRtrCacheServerTable_mib_index
                                                         * mib_idx);
    int             rpkiRtrCacheServerTable_index_from_oid(netsnmp_index *
                                                           oid_idx,
                                                           rpkiRtrCacheServerTable_mib_index
                                                           * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void           
        rpkiRtrCacheServerTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRCACHESERVERTABLE_INTERFACE_H */
/** @} */
