/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "rpkiRtrCacheServerTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "rpkiRtrCacheServerTable_interface.h"

netsnmp_feature_require(baby_steps)
    netsnmp_feature_require(row_merge)
    netsnmp_feature_require(check_all_requests_error)
#include <ctype.h>
/**********************************************************************
 **********************************************************************
 ***
 *** Table rpkiRtrCacheServerTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * RPKI-RTR-MIB::rpkiRtrCacheServerTable is subid 2 of rpkiRtrObjects.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.218.1.2, length: 9
     */
     typedef struct rpkiRtrCacheServerTable_interface_ctx_s {

         netsnmp_container *container;
         netsnmp_cache  *cache;

         rpkiRtrCacheServerTable_registration *user_ctx;

         netsnmp_table_registration_info tbl_info;

         netsnmp_baby_steps_access_methods access_multiplexer;

     } rpkiRtrCacheServerTable_interface_ctx;

     static rpkiRtrCacheServerTable_interface_ctx
         rpkiRtrCacheServerTable_if_ctx;

     static void    
         _rpkiRtrCacheServerTable_container_init
         (rpkiRtrCacheServerTable_interface_ctx * if_ctx);
     static void    
         _rpkiRtrCacheServerTable_container_shutdown
         (rpkiRtrCacheServerTable_interface_ctx * if_ctx);


netsnmp_container *rpkiRtrCacheServerTable_container_get(void)
{
    return rpkiRtrCacheServerTable_if_ctx.container;
}

rpkiRtrCacheServerTable_registration *
rpkiRtrCacheServerTable_registration_get(void)
{
    return rpkiRtrCacheServerTable_if_ctx.user_ctx;
}

rpkiRtrCacheServerTable_registration *
rpkiRtrCacheServerTable_registration_set
    (rpkiRtrCacheServerTable_registration * newreg)
{
    rpkiRtrCacheServerTable_registration *old =
        rpkiRtrCacheServerTable_if_ctx.user_ctx;
    rpkiRtrCacheServerTable_if_ctx.user_ctx = newreg;
    return old;
}

int
rpkiRtrCacheServerTable_container_size(void)
{
    return CONTAINER_SIZE(rpkiRtrCacheServerTable_if_ctx.container);
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_rpkiRtrCacheServerTable_pre_request;
static Netsnmp_Node_Handler _mfd_rpkiRtrCacheServerTable_post_request;
static Netsnmp_Node_Handler _mfd_rpkiRtrCacheServerTable_object_lookup;
static Netsnmp_Node_Handler _mfd_rpkiRtrCacheServerTable_get_values;
/**
 * @internal
 * Initialize the table rpkiRtrCacheServerTable 
 *    (Define its contents and how it's structured)
 */
void
_rpkiRtrCacheServerTable_initialize_interface
    (rpkiRtrCacheServerTable_registration * reg_ptr, u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &rpkiRtrCacheServerTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info =
        &rpkiRtrCacheServerTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int             mfd_modes = 0;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_rpkiRtrCacheServerTable_initialize_interface", "called\n"));


    /*************************************************
     *
     * save interface context for rpkiRtrCacheServerTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info, ASN_INTEGER,
                                               /** index: rpkiRtrCacheServerRemoteAddressType */
                                     ASN_OCTET_STR,
                                                 /** index: rpkiRtrCacheServerRemoteAddress */
                                     ASN_UNSIGNED,
                                                /** index: rpkiRtrCacheServerRemotePort */
                                     0);

    /*
     * Define the minimum and maximum accessible columns.  This
     * optimizes retrieval. 
     */
    tbl_info->min_column = RPKIRTRCACHESERVERTABLE_MIN_COL;
    tbl_info->max_column = RPKIRTRCACHESERVERTABLE_MAX_COL;

    /*
     * save users context
     */
    rpkiRtrCacheServerTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    rpkiRtrCacheServerTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _rpkiRtrCacheServerTable_container_init
        (&rpkiRtrCacheServerTable_if_ctx);
    if (NULL == rpkiRtrCacheServerTable_if_ctx.container) {
        snmp_log(LOG_ERR,
                 "could not initialize container for rpkiRtrCacheServerTable\n");
        return;
    }

    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup =
        _mfd_rpkiRtrCacheServerTable_object_lookup;
    access_multiplexer->get_values =
        _mfd_rpkiRtrCacheServerTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request =
        _mfd_rpkiRtrCacheServerTable_pre_request;
    access_multiplexer->post_request =
        _mfd_rpkiRtrCacheServerTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("rpkiRtrCacheServerTable:init_rpkiRtrCacheServerTable",
                "Registering rpkiRtrCacheServerTable as a mibs-for-dummies table.\n"));
    handler =
        netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo =
        netsnmp_handler_registration_create("rpkiRtrCacheServerTable",
                                            handler,
                                            rpkiRtrCacheServerTable_oid,
                                            rpkiRtrCacheServerTable_oid_size,
                                            HANDLER_CAN_BABY_STEP |
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                            HANDLER_CAN_RONLY
#else
                                            HANDLER_CAN_RONLY
#endif                          /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
        );
    if (NULL == reginfo) {
        snmp_log(LOG_ERR,
                 "error registering table rpkiRtrCacheServerTable\n");
        return;
    }
    reginfo->my_reg_void = &rpkiRtrCacheServerTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if (access_multiplexer->object_lookup)
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if (access_multiplexer->pre_request)
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if (access_multiplexer->post_request)
        mfd_modes |= BABY_STEP_POST_REQUEST;

#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if (access_multiplexer->set_values)
        mfd_modes |= BABY_STEP_SET_VALUES;
    if (access_multiplexer->irreversible_commit)
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if (access_multiplexer->object_syntax_checks)
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if (access_multiplexer->undo_setup)
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if (access_multiplexer->undo_cleanup)
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if (access_multiplexer->undo_sets)
        mfd_modes |= BABY_STEP_UNDO_SETS;

    if (access_multiplexer->row_creation)
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if (access_multiplexer->consistency_checks)
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if (access_multiplexer->commit)
        mfd_modes |= BABY_STEP_COMMIT;
    if (access_multiplexer->undo_commit)
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif                          /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */

    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            rpkiRtrCacheServerTable_if_ctx.
                                            container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject cache helper
     */
    if (NULL != rpkiRtrCacheServerTable_if_ctx.cache) {
        handler =
            netsnmp_cache_handler_get(rpkiRtrCacheServerTable_if_ctx.
                                      cache);
        netsnmp_inject_handler(reginfo, handler);
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

}                               /* _rpkiRtrCacheServerTable_initialize_interface */

/**
 * @internal
 * Shutdown the table rpkiRtrCacheServerTable
 */
void
_rpkiRtrCacheServerTable_shutdown_interface
    (rpkiRtrCacheServerTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _rpkiRtrCacheServerTable_container_shutdown
        (&rpkiRtrCacheServerTable_if_ctx);
}

void
rpkiRtrCacheServerTable_valid_columns_set(netsnmp_column_info *vc)
{
    rpkiRtrCacheServerTable_if_ctx.tbl_info.valid_columns = vc;
}                               /* rpkiRtrCacheServerTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
rpkiRtrCacheServerTable_index_to_oid(netsnmp_index * oid_idx,
                                     rpkiRtrCacheServerTable_mib_index *
                                     mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * rpkiRtrCacheServerRemoteAddressType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemoteAddressType;
    /*
     * rpkiRtrCacheServerRemoteAddress(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemoteAddress;
    /*
     * rpkiRtrCacheServerRemotePort(3)/InetPortNumber/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemotePort;

    /*
     * set up varbinds
     */
    memset(&var_rpkiRtrCacheServerRemoteAddressType, 0x00,
           sizeof(var_rpkiRtrCacheServerRemoteAddressType));
    var_rpkiRtrCacheServerRemoteAddressType.type = ASN_INTEGER;
    memset(&var_rpkiRtrCacheServerRemoteAddress, 0x00,
           sizeof(var_rpkiRtrCacheServerRemoteAddress));
    var_rpkiRtrCacheServerRemoteAddress.type = ASN_OCTET_STR;
    memset(&var_rpkiRtrCacheServerRemotePort, 0x00,
           sizeof(var_rpkiRtrCacheServerRemotePort));
    var_rpkiRtrCacheServerRemotePort.type = ASN_UNSIGNED;

    /*
     * chain temp index varbinds together
     */
    var_rpkiRtrCacheServerRemoteAddressType.next_variable =
        &var_rpkiRtrCacheServerRemoteAddress;
    var_rpkiRtrCacheServerRemoteAddress.next_variable =
        &var_rpkiRtrCacheServerRemotePort;
    var_rpkiRtrCacheServerRemotePort.next_variable = NULL;


    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_index_to_oid", "called\n"));

    /*
     * rpkiRtrCacheServerRemoteAddressType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    snmp_set_var_value(&var_rpkiRtrCacheServerRemoteAddressType,
                       &mib_idx->rpkiRtrCacheServerRemoteAddressType,
                       sizeof(mib_idx->
                              rpkiRtrCacheServerRemoteAddressType));

    /*
     * rpkiRtrCacheServerRemoteAddress(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    snmp_set_var_value(&var_rpkiRtrCacheServerRemoteAddress,
                       &mib_idx->rpkiRtrCacheServerRemoteAddress,
                       mib_idx->rpkiRtrCacheServerRemoteAddress_len *
                       sizeof(mib_idx->
                              rpkiRtrCacheServerRemoteAddress[0]));

    /*
     * rpkiRtrCacheServerRemotePort(3)/InetPortNumber/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H 
     */
    snmp_set_var_value(&var_rpkiRtrCacheServerRemotePort,
                       &mib_idx->rpkiRtrCacheServerRemotePort,
                       sizeof(mib_idx->rpkiRtrCacheServerRemotePort));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                            NULL, 0,
                            &var_rpkiRtrCacheServerRemoteAddressType);
    if (err)
        snmp_log(LOG_ERR, "error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_rpkiRtrCacheServerRemoteAddressType);

    return err;
}                               /* rpkiRtrCacheServerTable_index_to_oid */

/**
 * extract rpkiRtrCacheServerTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
rpkiRtrCacheServerTable_index_from_oid(netsnmp_index * oid_idx,
                                       rpkiRtrCacheServerTable_mib_index *
                                       mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * rpkiRtrCacheServerRemoteAddressType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemoteAddressType;
    /*
     * rpkiRtrCacheServerRemoteAddress(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemoteAddress;
    /*
     * rpkiRtrCacheServerRemotePort(3)/InetPortNumber/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_rpkiRtrCacheServerRemotePort;

    /*
     * set up varbinds
     */
    memset(&var_rpkiRtrCacheServerRemoteAddressType, 0x00,
           sizeof(var_rpkiRtrCacheServerRemoteAddressType));
    var_rpkiRtrCacheServerRemoteAddressType.type = ASN_INTEGER;
    memset(&var_rpkiRtrCacheServerRemoteAddress, 0x00,
           sizeof(var_rpkiRtrCacheServerRemoteAddress));
    var_rpkiRtrCacheServerRemoteAddress.type = ASN_OCTET_STR;
    memset(&var_rpkiRtrCacheServerRemotePort, 0x00,
           sizeof(var_rpkiRtrCacheServerRemotePort));
    var_rpkiRtrCacheServerRemotePort.type = ASN_UNSIGNED;

    /*
     * chain temp index varbinds together
     */
    var_rpkiRtrCacheServerRemoteAddressType.next_variable =
        &var_rpkiRtrCacheServerRemoteAddress;
    var_rpkiRtrCacheServerRemoteAddress.next_variable =
        &var_rpkiRtrCacheServerRemotePort;
    var_rpkiRtrCacheServerRemotePort.next_variable = NULL;


    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_index_from_oid", "called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(oid_idx->oids, oid_idx->len,
                            &var_rpkiRtrCacheServerRemoteAddressType);
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
        mib_idx->rpkiRtrCacheServerRemoteAddressType =
            *((u_long *) var_rpkiRtrCacheServerRemoteAddressType.val.
              string);
        /*
         * NOTE: val_len is in bytes, rpkiRtrCacheServerRemoteAddress_len might not be
         */
        if (var_rpkiRtrCacheServerRemoteAddress.val_len >
            sizeof(mib_idx->rpkiRtrCacheServerRemoteAddress))
            err = SNMP_ERR_GENERR;
        else {
            memcpy(mib_idx->rpkiRtrCacheServerRemoteAddress,
                   var_rpkiRtrCacheServerRemoteAddress.val.string,
                   var_rpkiRtrCacheServerRemoteAddress.val_len);
            mib_idx->rpkiRtrCacheServerRemoteAddress_len =
                var_rpkiRtrCacheServerRemoteAddress.val_len /
                sizeof(mib_idx->rpkiRtrCacheServerRemoteAddress[0]);
        }
        mib_idx->rpkiRtrCacheServerRemotePort =
            *((u_long *) var_rpkiRtrCacheServerRemotePort.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_rpkiRtrCacheServerRemoteAddressType);

    return err;
}                               /* rpkiRtrCacheServerTable_index_from_oid */


/*
 *********************************************************************
 * @internal
 * allocate resources for a rpkiRtrCacheServerTable_rowreq_ctx
 */
rpkiRtrCacheServerTable_rowreq_ctx *
rpkiRtrCacheServerTable_allocate_rowreq_ctx(void)
{
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx =
        SNMP_MALLOC_TYPEDEF(rpkiRtrCacheServerTable_rowreq_ctx);

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_allocate_rowreq_ctx", "called\n"));

    if (NULL == rowreq_ctx) {
        snmp_log(LOG_ERR, "Couldn't allocate memory for a "
                 "rpkiRtrCacheServerTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->rpkiRtrCacheServerTable_data_list = NULL;


    return rowreq_ctx;
}                               /* rpkiRtrCacheServerTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a rpkiRtrCacheServerTable_rowreq_ctx
 */
void
rpkiRtrCacheServerTable_release_rowreq_ctx
    (rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_release_rowreq_ctx", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);


    /*
     * free index oid pointer
     */
    if (rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
}                               /* rpkiRtrCacheServerTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rpkiRtrCacheServerTable_pre_request(netsnmp_mib_handler *handler,
                                         netsnmp_handler_registration
                                         *reginfo,
                                         netsnmp_agent_request_info
                                         *agtreq_info,
                                         netsnmp_request_info *requests)
{
    int             rc;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_pre_request", "called\n"));

    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:rpkiRtrCacheServerTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }

    rc = rpkiRtrCacheServerTable_pre_request
        (rpkiRtrCacheServerTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rpkiRtrCacheServerTable", "error %d from "
                    "rpkiRtrCacheServerTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_rpkiRtrCacheServerTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rpkiRtrCacheServerTable_post_request(netsnmp_mib_handler *handler,
                                          netsnmp_handler_registration
                                          *reginfo,
                                          netsnmp_agent_request_info
                                          *agtreq_info,
                                          netsnmp_request_info *requests)
{
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx =
        (rpkiRtrCacheServerTable_rowreq_ctx *)
        netsnmp_container_table_row_extract(requests);
    int             rc, packet_rc;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_post_request", "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        rpkiRtrCacheServerTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:rpkiRtrCacheServerTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }

    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    rc = rpkiRtrCacheServerTable_post_request
        (rpkiRtrCacheServerTable_if_ctx.user_ctx, packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rpkiRtrCacheServerTable", "error %d from "
                    "rpkiRtrCacheServerTable_post_request\n", rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_rpkiRtrCacheServerTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rpkiRtrCacheServerTable_object_lookup(netsnmp_mib_handler *handler,
                                           netsnmp_handler_registration
                                           *reginfo,
                                           netsnmp_agent_request_info
                                           *agtreq_info,
                                           netsnmp_request_info *requests)
{
    int             rc = SNMP_ERR_NOERROR;
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx =
        (rpkiRtrCacheServerTable_rowreq_ctx *)
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_object_lookup", "called\n"));

    /*
     * get our context from mfd
     * rpkiRtrCacheServerTable_interface_ctx *if_ctx =
     *             (rpkiRtrCacheServerTable_interface_ctx *)reginfo->my_reg_void;
     */

    if (NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        rpkiRtrCacheServerTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
}                               /* _mfd_rpkiRtrCacheServerTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_rpkiRtrCacheServerTable_get_column(rpkiRtrCacheServerTable_rowreq_ctx *
                                    rowreq_ctx,
                                    netsnmp_variable_list * var,
                                    int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_get_column", "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * rpkiRtrCacheServerLocalAddressType(4)/InetAddressType/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERLOCALADDRESSTYPE:
        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = rpkiRtrCacheServerLocalAddressType_get(rowreq_ctx,
                                                    (u_long *) var->val.
                                                    string);
        break;

        /*
         * rpkiRtrCacheServerLocalAddress(5)/InetAddress/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERLOCALADDRESS:
        var->type = ASN_OCTET_STR;
        rc = rpkiRtrCacheServerLocalAddress_get(rowreq_ctx,
                                                (char **) &var->val.string,
                                                &var->val_len);
        break;

        /*
         * rpkiRtrCacheServerLocalPort(6)/InetPortNumber/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/R/d/H 
         */
    case COLUMN_RPKIRTRCACHESERVERLOCALPORT:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerLocalPort_get(rowreq_ctx,
                                             (u_long *) var->val.string);
        break;

        /*
         * rpkiRtrCacheServerPreference(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/D/h 
         */
    case COLUMN_RPKIRTRCACHESERVERPREFERENCE:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerPreference_get(rowreq_ctx,
                                              (u_long *) var->val.string);
        break;

        /*
         * rpkiRtrCacheServerConnectionType(8)/RpkiRtrConnectionType/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERCONNECTIONTYPE:
        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = rpkiRtrCacheServerConnectionType_get(rowreq_ctx,
                                                  (u_long *) var->val.
                                                  string);
        break;

        /*
         * rpkiRtrCacheServerConnectionStatus(9)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERCONNECTIONSTATUS:
        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = rpkiRtrCacheServerConnectionStatus_get(rowreq_ctx,
                                                    (u_long *) var->val.
                                                    string);
        break;

        /*
         * rpkiRtrCacheServerDescription(10)/LongUtf8String/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H 
         */
    case COLUMN_RPKIRTRCACHESERVERDESCRIPTION:
        var->type = ASN_OCTET_STR;
        rc = rpkiRtrCacheServerDescription_get(rowreq_ctx,
                                               (char **) &var->val.string,
                                               &var->val_len);
        break;

        /*
         * rpkiRtrCacheServerMsgsReceived(11)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERMSGSRECEIVED:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerMsgsReceived_get(rowreq_ctx,
                                                (u_long *) var->val.
                                                string);
        break;

        /*
         * rpkiRtrCacheServerMsgsSent(12)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERMSGSSENT:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerMsgsSent_get(rowreq_ctx,
                                            (u_long *) var->val.string);
        break;

        /*
         * rpkiRtrCacheServerV4ActiveRecords(13)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV4ACTIVERECORDS:
        var->val_len = sizeof(u_long);
        var->type = ASN_GAUGE;
        rc = rpkiRtrCacheServerV4ActiveRecords_get(rowreq_ctx,
                                                   (u_long *) var->val.
                                                   string);
        break;

        /*
         * rpkiRtrCacheServerV4Announcements(14)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV4ANNOUNCEMENTS:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerV4Announcements_get(rowreq_ctx,
                                                   (u_long *) var->val.
                                                   string);
        break;

        /*
         * rpkiRtrCacheServerV4Withdrawals(15)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV4WITHDRAWALS:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerV4Withdrawals_get(rowreq_ctx,
                                                 (u_long *) var->val.
                                                 string);
        break;

        /*
         * rpkiRtrCacheServerV6ActiveRecords(16)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV6ACTIVERECORDS:
        var->val_len = sizeof(u_long);
        var->type = ASN_GAUGE;
        rc = rpkiRtrCacheServerV6ActiveRecords_get(rowreq_ctx,
                                                   (u_long *) var->val.
                                                   string);
        break;

        /*
         * rpkiRtrCacheServerV6Announcements(17)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV6ANNOUNCEMENTS:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerV6Announcements_get(rowreq_ctx,
                                                   (u_long *) var->val.
                                                   string);
        break;

        /*
         * rpkiRtrCacheServerV6Withdrawals(18)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERV6WITHDRAWALS:
        var->val_len = sizeof(u_long);
        var->type = ASN_COUNTER;
        rc = rpkiRtrCacheServerV6Withdrawals_get(rowreq_ctx,
                                                 (u_long *) var->val.
                                                 string);
        break;

        /*
         * rpkiRtrCacheServerLatestSerial(19)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERLATESTSERIAL:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerLatestSerial_get(rowreq_ctx,
                                                (u_long *) var->val.
                                                string);
        break;

        /*
         * rpkiRtrCacheServerSessionID(20)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/R/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERSESSIONID:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerSessionID_get(rowreq_ctx,
                                             (u_long *) var->val.string);
        break;

        /*
         * rpkiRtrCacheServerRefreshTimer(21)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/R/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERREFRESHTIMER:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerRefreshTimer_get(rowreq_ctx,
                                                (u_long *) var->val.
                                                string);
        break;

        /*
         * rpkiRtrCacheServerTimeToRefresh(22)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERTIMETOREFRESH:
        var->val_len = sizeof(long);
        var->type = ASN_INTEGER;
        rc = rpkiRtrCacheServerTimeToRefresh_get(rowreq_ctx,
                                                 (long *) var->val.string);
        break;

        /*
         * rpkiRtrCacheServerId(23)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/R/d/h 
         */
    case COLUMN_RPKIRTRCACHESERVERID:
        var->val_len = sizeof(u_long);
        var->type = ASN_UNSIGNED;
        rc = rpkiRtrCacheServerId_get(rowreq_ctx,
                                      (u_long *) var->val.string);
        break;

    default:
        if (RPKIRTRCACHESERVERTABLE_MIN_COL <= column
            && column <= RPKIRTRCACHESERVERTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_get_column", "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                     "unknown column %d in _rpkiRtrCacheServerTable_get_column\n",
                     column);
        }
        break;
    }

    return rc;
}                               /* _rpkiRtrCacheServerTable_get_column */

int
_mfd_rpkiRtrCacheServerTable_get_values(netsnmp_mib_handler *handler,
                                        netsnmp_handler_registration
                                        *reginfo,
                                        netsnmp_agent_request_info
                                        *agtreq_info,
                                        netsnmp_request_info *requests)
{
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx =
        (rpkiRtrCacheServerTable_rowreq_ctx *)
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    u_char         *old_string;
    void            (*dataFreeHook) (void *);
    int             rc;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_mfd_rpkiRtrCacheServerTable_get_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    for (; requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if (NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len =
                sizeof(requests->requestvb->buf);
        } else if (requests->requestvb->buf ==
                   requests->requestvb->val.string) {
            if (requests->requestvb->val_len !=
                sizeof(requests->requestvb->buf))
                requests->requestvb->val_len =
                    sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _rpkiRtrCacheServerTable_get_column(rowreq_ctx,
                                                 requests->requestvb,
                                                 tri->colnum);
        if (rc) {
            if (MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        } else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR, "NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if (rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if (old_string && (old_string != requests->requestvb->buf) &&
            (requests->requestvb->val.string != old_string)) {
            if (dataFreeHook)
                (*dataFreeHook) (old_string);
            else
                free(old_string);
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_rpkiRtrCacheServerTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * SET PROCESSING NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void     _container_free(netsnmp_container * container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_cache_load",
                "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache for rpkiRtrCacheServerTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    /*
     * call user code
     */
    return rpkiRtrCacheServerTable_container_load((netsnmp_container *)
                                                  cache->magic);
}                               /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_cache_free",
                "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache in rpkiRtrCacheServerTable_cache_free\n");
        return;
    }

    container = (netsnmp_container *) cache->magic;

    _container_free(container);
}                               /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(rpkiRtrCacheServerTable_rowreq_ctx * rowreq_ctx,
                     void *context)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_container_item_free",
                "called\n"));

    if (NULL == rowreq_ctx)
        return;

    rpkiRtrCacheServerTable_release_rowreq_ctx(rowreq_ctx);
}                               /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_container_free",
                "called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR,
                 "invalid container in rpkiRtrCacheServerTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    rpkiRtrCacheServerTable_container_free(container);

    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *) _container_item_free,
                    NULL);
}                               /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_rpkiRtrCacheServerTable_container_init
    (rpkiRtrCacheServerTable_interface_ctx * if_ctx)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_rpkiRtrCacheServerTable_container_init", "called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30,    /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         rpkiRtrCacheServerTable_oid,
                                         rpkiRtrCacheServerTable_oid_size);

    if (NULL == if_ctx->cache) {
        snmp_log(LOG_ERR,
                 "error creating cache for rpkiRtrCacheServerTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    rpkiRtrCacheServerTable_container_init(&if_ctx->container,
                                           if_ctx->cache);
    if (NULL == if_ctx->container)
        if_ctx->container =
            netsnmp_container_find
            ("rpkiRtrCacheServerTable:table_container");
    if (NULL == if_ctx->container) {
        snmp_log(LOG_ERR, "error creating container in "
                 "rpkiRtrCacheServerTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void *) if_ctx->container;
}                               /* _rpkiRtrCacheServerTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_rpkiRtrCacheServerTable_container_shutdown
    (rpkiRtrCacheServerTable_interface_ctx * if_ctx)
{
    DEBUGMSGTL(("internal:rpkiRtrCacheServerTable:_rpkiRtrCacheServerTable_container_shutdown", "called\n"));

    rpkiRtrCacheServerTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

}                               /* _rpkiRtrCacheServerTable_container_shutdown */


rpkiRtrCacheServerTable_rowreq_ctx *
rpkiRtrCacheServerTable_row_find_by_mib_index
    (rpkiRtrCacheServerTable_mib_index * mib_idx)
{
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx;
    oid             oid_tmp[MAX_OID_LEN];
    netsnmp_index   oid_idx;
    int             rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp) / sizeof(oid);

    /*
     * convert
     */
    rc = rpkiRtrCacheServerTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx =
        (rpkiRtrCacheServerTable_rowreq_ctx *)
        CONTAINER_FIND(rpkiRtrCacheServerTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}
