/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bird-rpki-client.h"


/*
 * include our parent header 
 */
#include "rpkiRtrCacheServerTable.h"


#include "rpkiRtrCacheServerTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rpkiRtrCacheServerTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RPKI-RTR-MIB::rpkiRtrCacheServerTable is subid 2 of rpkiRtrObjects.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.218.1.2, length: 9
 */

/**
 * initialization for rpkiRtrCacheServerTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param rpkiRtrCacheServerTable_reg
 *        Pointer to rpkiRtrCacheServerTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
rpkiRtrCacheServerTable_init_data(rpkiRtrCacheServerTable_registration *
                                  rpkiRtrCacheServerTable_reg)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize rpkiRtrCacheServerTable data.
     */

    return MFD_SUCCESS;
}                               /* rpkiRtrCacheServerTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
rpkiRtrCacheServerTable_container_init(netsnmp_container **
                                       container_ptr_ptr,
                                       netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to rpkiRtrCacheServerTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,
                 "bad cache param to rpkiRtrCacheServerTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up rpkiRtrCacheServerTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = RPKIRTRCACHESERVERTABLE_CACHE_TIMEOUT;     /* seconds */
}                               /* rpkiRtrCacheServerTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before rpkiRtrCacheServerTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
rpkiRtrCacheServerTable_container_shutdown(netsnmp_container *
                                           container_ptr)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to rpkiRtrCacheServerTable_container_shutdown\n");
        return;
    }

}                               /* rpkiRtrCacheServerTable_container_shutdown */


int
rpkiRtrCacheServerTable_data_from_sockaddr(struct sockaddr_storage *ss,
					   u_long   *AddressType,
					   char      Address[],
					   size_t   *AddressLen,
					   u_long   *Port) {

    if (AF_INET == ss->ss_family) {
      struct sockaddr_in *sin = (struct sockaddr_in *)ss;
      *AddressType = INETADDRESSTYPE_IPV4;
      *AddressLen = (sizeof(sin->sin_addr.s_addr) < *AddressLen ? sizeof(sin->sin_addr.s_addr) : *AddressLen);
      memcpy(Address, &(sin->sin_addr.s_addr), *AddressLen);
      *Port = sin->sin_port;
    }
    else if (AF_INET6 == ss->ss_family) {
      struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)ss;
      *AddressType = INETADDRESSTYPE_IPV6;
      *AddressLen = (sizeof(sin6->sin6_addr.s6_addr) < *AddressLen ? sizeof(sin6->sin6_addr.s6_addr) : *AddressLen);
      memcpy(Address, &(sin6->sin6_addr.s6_addr), *AddressLen);
      *Port = sin6->sin6_port;
    }
    else {
      return 0;
    }
    return 1;
}


/**
 * load initial data
 *
 * TODO:350:M: Implement rpkiRtrCacheServerTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  rpkiRtrCacheServerTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
rpkiRtrCacheServerTable_container_load(netsnmp_container * container)
{
    rpkiRtrCacheServerTable_rowreq_ctx *rowreq_ctx;
    int      count = 0;

    struct sockaddr_storage ss;
    size_t ss_size = sizeof(struct sockaddr_storage);

    struct tr_tcp_socket  *tt_socket = (struct tr_tcp_socket *)bgpsec_bc_rtr_config->groups->sockets[0]->tr_socket->socket;

    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_container_load", "called\n"));

    if (-1 == getpeername(tt_socket->socket,
			  (struct sockaddr *)&ss,
			  (socklen_t *)&ss_size)) {
      return MFD_RESOURCE_UNAVAILABLE;
    }

    u_long   RemoteAddressType;
    char     RemoteAddress[113];
    memset(RemoteAddress, 0, sizeof(RemoteAddress));
    size_t   RemoteAddressLen;
    u_long   RemotePort;

    if ( 0 ==
	 rpkiRtrCacheServerTable_data_from_sockaddr(&ss,
						    &RemoteAddressType,
						    RemoteAddress,
						    &RemoteAddressLen,
						    &RemotePort) ) {
      return MFD_RESOURCE_UNAVAILABLE;
    }

    rowreq_ctx = rpkiRtrCacheServerTable_allocate_rowreq_ctx();
    if (NULL == rowreq_ctx) {
      snmp_log(LOG_ERR, "memory allocation failed\n");
      return MFD_RESOURCE_UNAVAILABLE;
    }
    if ( MFD_SUCCESS !=
	 rpkiRtrCacheServerTable_indexes_set(rowreq_ctx,
					     RemoteAddressType,
					     RemoteAddress,
					     RemoteAddressLen,
					     RemotePort) )
      {
	snmp_log(LOG_ERR,
		 "error setting index while loading "
		 "rpkiRtrCacheServerTable data.\n");
	rpkiRtrCacheServerTable_release_rowreq_ctx(rowreq_ctx);
	return MFD_RESOURCE_UNAVAILABLE;
      }

    if (-1 == getsockname(tt_socket->socket,
			  (struct sockaddr *)&ss,
			  (socklen_t *)&ss_size)) {
	rpkiRtrCacheServerTable_release_rowreq_ctx(rowreq_ctx);
	return MFD_RESOURCE_UNAVAILABLE;
    }

    rowreq_ctx->data.rpkiRtrCacheServerLocalAddress_len =
      sizeof(rowreq_ctx->data.rpkiRtrCacheServerLocalAddress);
    
    if ( 0 ==
	 rpkiRtrCacheServerTable_data_from_sockaddr
	 (&ss,
	  &(rowreq_ctx->data.rpkiRtrCacheServerLocalAddressType),
	  rowreq_ctx->data.rpkiRtrCacheServerLocalAddress,
	  &(rowreq_ctx->data.rpkiRtrCacheServerLocalAddress_len),

	  &(rowreq_ctx->data.rpkiRtrCacheServerLocalPort)) ) {

      rpkiRtrCacheServerTable_release_rowreq_ctx(rowreq_ctx);
      return MFD_RESOURCE_UNAVAILABLE;
    }

    rowreq_ctx->data.rpkiRtrCacheServerPreference =
      bgpsec_bc_rtr_config->groups->preference;

    rowreq_ctx->data.rpkiRtrCacheServerConnectionType =
      RPKIRTRCONNECTIONTYPE_TCP;

    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable",
		" connection type is %s\n",
		rtr_mgr_status_to_str(bgpsec_bc_rtr_config->groups->status) ));
/*		rtr_mgr_status_to_str(bgpsec_bc_rtr_config->groups->status) )); */

    if ( RTR_MGR_ESTABLISHED == bgpsec_bc_rtr_config->groups->status) {
      rowreq_ctx->data.rpkiRtrCacheServerConnectionStatus =
	RPKIRTRCACHESERVERCONNECTIONSTATUS_UP;
    }
    else {
      rowreq_ctx->data.rpkiRtrCacheServerConnectionStatus =
	RPKIRTRCACHESERVERCONNECTIONSTATUS_DOWN;
    }

    memset(rowreq_ctx->data.rpkiRtrCacheServerDescription, 0,
	   sizeof(rowreq_ctx->data.rpkiRtrCacheServerDescription));
    rowreq_ctx->data.rpkiRtrCacheServerDescription_len = 0;
    
    rowreq_ctx->data.rpkiRtrCacheServerMsgsReceived = 0;

    rowreq_ctx->data.rpkiRtrCacheServerMsgsSent = 0;

    rowreq_ctx->data.rpkiRtrCacheServerV4ActiveRecords = 0;

    rowreq_ctx->data.rpkiRtrCacheServerV4Announcements = 0;
    
    rowreq_ctx->data.rpkiRtrCacheServerV4Withdrawals = 0;

    rowreq_ctx->data.rpkiRtrCacheServerV6ActiveRecords = 0;

    rowreq_ctx->data.rpkiRtrCacheServerV6Announcements = 0;

    rowreq_ctx->data.rpkiRtrCacheServerV6Withdrawals = 0;

    rowreq_ctx->data.rpkiRtrCacheServerLatestSerial =
      bgpsec_bc_rtr_config->groups->sockets[0]->serial_number;

    rowreq_ctx->data.rpkiRtrCacheServerSessionID=
      bgpsec_bc_rtr_config->groups->sockets[0]->session_id;

    rowreq_ctx->data.rpkiRtrCacheServerRefreshTimer =
	bgpsec_bc_rtr_config->groups->sockets[0]->refresh_interval;
   
    time_t cur_time;
    lrtr_get_monotonic_time(&cur_time);
    rowreq_ctx->data.rpkiRtrCacheServerTimeToRefresh =
      (bgpsec_bc_rtr_config->groups->sockets[0]->last_update +
       bgpsec_bc_rtr_config->groups->sockets[0]->refresh_interval) - cur_time;

    /* only 1 group currently */
    rowreq_ctx->data.rpkiRtrCacheServerId = 0;
    
    /*
     * insert into table container
     */
    CONTAINER_INSERT(container, rowreq_ctx);
    ++count;
    
    DEBUGMSGT(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_container_load", "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* rpkiRtrCacheServerTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
rpkiRtrCacheServerTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free rpkiRtrCacheServerTable container data.
     */
}                               /* rpkiRtrCacheServerTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
rpkiRtrCacheServerTable_row_prep(rpkiRtrCacheServerTable_rowreq_ctx *
                                 rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* rpkiRtrCacheServerTable_row_prep */

/** @} */
