/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef RPKIRTRCACHESERVERTABLE_DATA_ACCESS_H
#define RPKIRTRCACHESERVERTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rpkiRtrCacheServerTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * RPKI-RTR-MIB::rpkiRtrCacheServerTable is subid 2 of rpkiRtrObjects.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.218.1.2, length: 9
     */


    int            
        rpkiRtrCacheServerTable_init_data
        (rpkiRtrCacheServerTable_registration *
         rpkiRtrCacheServerTable_reg);


    /*
     * TODO:180:o: Review rpkiRtrCacheServerTable cache timeout.
     * The number of seconds before the cache times out
     */
#define RPKIRTRCACHESERVERTABLE_CACHE_TIMEOUT   10

    void           
        rpkiRtrCacheServerTable_container_init(netsnmp_container **
                                               container_ptr_ptr,
                                               netsnmp_cache * cache);
    void           
        rpkiRtrCacheServerTable_container_shutdown(netsnmp_container *
                                                   container_ptr);

    int            
        rpkiRtrCacheServerTable_container_load(netsnmp_container *
                                               container);
    void           
        rpkiRtrCacheServerTable_container_free(netsnmp_container *
                                               container);

    int             rpkiRtrCacheServerTable_cache_load(netsnmp_container *
                                                       container);
    void            rpkiRtrCacheServerTable_cache_free(netsnmp_container *
                                                       container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int            
        rpkiRtrCacheServerTable_row_prep(rpkiRtrCacheServerTable_rowreq_ctx
                                         * rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRCACHESERVERTABLE_DATA_ACCESS_H */
