/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef RPKIRTRPREFIXORIGINTABLE_INTERFACE_H
#define RPKIRTRPREFIXORIGINTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "rpkiRtrPrefixOriginTable.h"

    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _rpkiRtrPrefixOriginTable_initialize_interface
        (rpkiRtrPrefixOriginTable_registration * user_ctx, u_long flags);
    void           
        _rpkiRtrPrefixOriginTable_shutdown_interface
        (rpkiRtrPrefixOriginTable_registration * user_ctx);

    rpkiRtrPrefixOriginTable_registration
        *rpkiRtrPrefixOriginTable_registration_get(void);

    rpkiRtrPrefixOriginTable_registration
        *rpkiRtrPrefixOriginTable_registration_set
        (rpkiRtrPrefixOriginTable_registration * newreg);

    netsnmp_container *rpkiRtrPrefixOriginTable_container_get(void);
    int             rpkiRtrPrefixOriginTable_container_size(void);

    rpkiRtrPrefixOriginTable_rowreq_ctx
        *rpkiRtrPrefixOriginTable_allocate_rowreq_ctx(void);

    void
    rpkiRtrPrefixOriginTable_release_rowreq_ctx
    (rpkiRtrPrefixOriginTable_rowreq_ctx * rowreq_ctx);

    int  rpkiRtrPrefixOriginTable_index_to_oid
         (netsnmp_index *                      oid_idx,
	  rpkiRtrPrefixOriginTable_mib_index * mib_idx);
    int  rpkiRtrPrefixOriginTable_index_from_oid
         (netsnmp_index *                      oid_idx,
	  rpkiRtrPrefixOriginTable_mib_index * mib_idx);
  
    /*
     * access to certain internals. use with caution!
     */
    void           
    rpkiRtrPrefixOriginTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRPREFIXORIGINTABLE_INTERFACE_H */
/** @} */
