/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef RPKIRTRPREFIXORIGINTABLE_OIDS_H
#define RPKIRTRPREFIXORIGINTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table rpkiRtrPrefixOriginTable 
     */
#define RPKIRTRPREFIXORIGINTABLE_OID              1,3,6,1,2,1,218,1,4


#define COLUMN_RPKIRTRPREFIXORIGINADDRESSTYPE         1

#define COLUMN_RPKIRTRPREFIXORIGINADDRESS         2

#define COLUMN_RPKIRTRPREFIXORIGINMINLENGTH         3

#define COLUMN_RPKIRTRPREFIXORIGINMAXLENGTH         4

#define COLUMN_RPKIRTRPREFIXORIGINASN         5

#define COLUMN_RPKIRTRPREFIXORIGINCACHESERVERID         6


#define RPKIRTRPREFIXORIGINTABLE_MIN_COL   COLUMN_RPKIRTRPREFIXORIGINCACHESERVERID
#define RPKIRTRPREFIXORIGINTABLE_MAX_COL   COLUMN_RPKIRTRPREFIXORIGINCACHESERVERID



#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRPREFIXORIGINTABLE_OIDS_H */
