/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for rpkiRtrCacheServerTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "rpkiRtrCacheServerTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "rpkiRtrCacheServerTable_interface.h"

const oid       rpkiRtrCacheServerTable_oid[] =
    { RPKIRTRCACHESERVERTABLE_OID };
const int       rpkiRtrCacheServerTable_oid_size =
OID_LENGTH(rpkiRtrCacheServerTable_oid);

rpkiRtrCacheServerTable_registration rpkiRtrCacheServerTable_user_context;

void            initialize_table_rpkiRtrCacheServerTable(void);
void            shutdown_table_rpkiRtrCacheServerTable(void);


/**
 * Initializes the rpkiRtrCacheServerTable module
 */
void
init_rpkiRtrCacheServerTable(void)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:init_rpkiRtrCacheServerTable", "called\n"));

    /*
     * TODO:300:o: Perform rpkiRtrCacheServerTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("rpkiRtrCacheServerTable"))
        initialize_table_rpkiRtrCacheServerTable();

}                               /* init_rpkiRtrCacheServerTable */

/**
 * Shut-down the rpkiRtrCacheServerTable module (agent is exiting)
 */
void
shutdown_rpkiRtrCacheServerTable(void)
{
    if (should_init("rpkiRtrCacheServerTable"))
        shutdown_table_rpkiRtrCacheServerTable();

}

/**
 * Initialize the table rpkiRtrCacheServerTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_rpkiRtrCacheServerTable(void)
{
    rpkiRtrCacheServerTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:initialize_table_rpkiRtrCacheServerTable", "called\n"));

    /*
     * TODO:301:o: Perform rpkiRtrCacheServerTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize rpkiRtrCacheServerTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("rpkiRtrCacheServerTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _rpkiRtrCacheServerTable_initialize_interface(user_context, flags);
}                               /* initialize_table_rpkiRtrCacheServerTable */

/**
 * Shutdown the table rpkiRtrCacheServerTable 
 */
void
shutdown_table_rpkiRtrCacheServerTable(void)
{
    /*
     * call interface shutdown code
     */
    _rpkiRtrCacheServerTable_shutdown_interface
        (&rpkiRtrCacheServerTable_user_context);
}

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
rpkiRtrCacheServerTable_pre_request(rpkiRtrCacheServerTable_registration *
                                    user_context)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_pre_request", "called\n"));

    /*
     * TODO:510:o: Perform rpkiRtrCacheServerTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* rpkiRtrCacheServerTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
rpkiRtrCacheServerTable_post_request(rpkiRtrCacheServerTable_registration *
                                     user_context, int rc)
{
    DEBUGMSGTL(("verbose:rpkiRtrCacheServerTable:rpkiRtrCacheServerTable_post_request", "called\n"));

    /*
     * TODO:511:o: Perform rpkiRtrCacheServerTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* rpkiRtrCacheServerTable_post_request */


/** @{ */
