/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for rpkiRtrPrefixOriginTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>


/*
 * include our parent header 
 */
#include "rpkiRtrPrefixOriginTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "rpkiRtrPrefixOriginTable_interface.h"

const oid       rpkiRtrPrefixOriginTable_oid[] =
    { RPKIRTRPREFIXORIGINTABLE_OID };
const int       rpkiRtrPrefixOriginTable_oid_size =
OID_LENGTH(rpkiRtrPrefixOriginTable_oid);

rpkiRtrPrefixOriginTable_registration
    rpkiRtrPrefixOriginTable_user_context;

void            initialize_table_rpkiRtrPrefixOriginTable(void);
void            shutdown_table_rpkiRtrPrefixOriginTable(void);


/**
 * Initializes the rpkiRtrPrefixOriginTable module
 */
void
init_rpkiRtrPrefixOriginTable(void)
{
    DEBUGMSGTL(("verbose:rpkiRtrPrefixOriginTable:init_rpkiRtrPrefixOriginTable", "called\n"));

    /*
     * TODO:300:o: Perform rpkiRtrPrefixOriginTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("rpkiRtrPrefixOriginTable"))
        initialize_table_rpkiRtrPrefixOriginTable();

}                               /* init_rpkiRtrPrefixOriginTable */

/**
 * Shut-down the rpkiRtrPrefixOriginTable module (agent is exiting)
 */
void
shutdown_rpkiRtrPrefixOriginTable(void)
{
    if (should_init("rpkiRtrPrefixOriginTable"))
        shutdown_table_rpkiRtrPrefixOriginTable();

}

/**
 * Initialize the table rpkiRtrPrefixOriginTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_rpkiRtrPrefixOriginTable(void)
{
    rpkiRtrPrefixOriginTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:rpkiRtrPrefixOriginTable:initialize_table_rpkiRtrPrefixOriginTable", "called\n"));

    /*
     * TODO:301:o: Perform rpkiRtrPrefixOriginTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize rpkiRtrPrefixOriginTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("rpkiRtrPrefixOriginTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _rpkiRtrPrefixOriginTable_initialize_interface(user_context, flags);
}                               /* initialize_table_rpkiRtrPrefixOriginTable */

/**
 * Shutdown the table rpkiRtrPrefixOriginTable 
 */
void
shutdown_table_rpkiRtrPrefixOriginTable(void)
{
    /*
     * call interface shutdown code
     */
    _rpkiRtrPrefixOriginTable_shutdown_interface
        (&rpkiRtrPrefixOriginTable_user_context);
}

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
rpkiRtrPrefixOriginTable_pre_request(rpkiRtrPrefixOriginTable_registration
                                     * user_context)
{
    DEBUGMSGTL(("verbose:rpkiRtrPrefixOriginTable:rpkiRtrPrefixOriginTable_pre_request", "called\n"));

    /*
     * TODO:510:o: Perform rpkiRtrPrefixOriginTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* rpkiRtrPrefixOriginTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
rpkiRtrPrefixOriginTable_post_request(rpkiRtrPrefixOriginTable_registration
                                      * user_context, int rc)
{
    DEBUGMSGTL(("verbose:rpkiRtrPrefixOriginTable:rpkiRtrPrefixOriginTable_post_request", "called\n"));

    /*
     * TODO:511:o: Perform rpkiRtrPrefixOriginTable post-request actions.
     */

    return MFD_SUCCESS;
}       /* rpkiRtrPrefixOriginTable_post_request */


/** @{ */



