/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef RPKIRTRCACHESERVERTABLE_ENUMS_H
#define RPKIRTRCACHESERVERTABLE_ENUMS_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     * NOTES on enums
     * ==============
     *
     * Value Mapping
     * -------------
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them
     * below. For example, a boolean flag (1/0) is usually represented
     * as a TruthValue in a MIB, which maps to the values (1/2).
     *
     */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table rpkiRtrCacheServerTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * rpkiRtrCacheServerRemoteAddressType (InetAddressType / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef INETADDRESSTYPE_ENUMS
#define INETADDRESSTYPE_ENUMS

#define INETADDRESSTYPE_UNKNOWN  0
#define INETADDRESSTYPE_IPV4  1
#define INETADDRESSTYPE_IPV6  2
#define INETADDRESSTYPE_IPV4Z  3
#define INETADDRESSTYPE_IPV6Z  4
#define INETADDRESSTYPE_DNS  16

#endif                          /* INETADDRESSTYPE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * rpkiRtrCacheServerLocalAddressType (InetAddressType / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef INETADDRESSTYPE_ENUMS
#define INETADDRESSTYPE_ENUMS

#define INETADDRESSTYPE_UNKNOWN  0
#define INETADDRESSTYPE_IPV4  1
#define INETADDRESSTYPE_IPV6  2
#define INETADDRESSTYPE_IPV4Z  3
#define INETADDRESSTYPE_IPV6Z  4
#define INETADDRESSTYPE_DNS  16

#endif                          /* INETADDRESSTYPE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * rpkiRtrCacheServerConnectionType (RpkiRtrConnectionType / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RPKIRTRCONNECTIONTYPE_ENUMS
#define RPKIRTRCONNECTIONTYPE_ENUMS

#define RPKIRTRCONNECTIONTYPE_SSH  1
#define RPKIRTRCONNECTIONTYPE_TLS  2
#define RPKIRTRCONNECTIONTYPE_TCPMD5  3
#define RPKIRTRCONNECTIONTYPE_TCPAO  4
#define RPKIRTRCONNECTIONTYPE_TCP  5
#define RPKIRTRCONNECTIONTYPE_IPSEC  6
#define RPKIRTRCONNECTIONTYPE_OTHER  7

#endif                          /* RPKIRTRCONNECTIONTYPE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * rpkiRtrCacheServerConnectionStatus (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RPKIRTRCACHESERVERCONNECTIONSTATUS_ENUMS
#define RPKIRTRCACHESERVERCONNECTIONSTATUS_ENUMS

#define RPKIRTRCACHESERVERCONNECTIONSTATUS_UP  1
#define RPKIRTRCACHESERVERCONNECTIONSTATUS_DOWN  2

#endif                          /* RPKIRTRCACHESERVERCONNECTIONSTATUS_ENUMS */




#ifdef __cplusplus
}
#endif
#endif                          /* RPKIRTRCACHESERVERTABLE_ENUMS_H */
